services:
  - type: web
    name: shincom-app
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
    autoDeploy: true

  - type: web
    name: shincom-unified
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -t 120 app:app
    envVars:
      - key: PORT
        value: 10000
