services:
  - type: web
    name: shincom-unified
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -t 600 app:app
    envVars:
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
    autoDeploy: true
